### ISSUE TITLE
[PE-D][Tester D] Help window shows an empty white screen

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-W14-1/tp#147]
![image.png](https://raw.githubusercontent.com/t1mzzz/ped/main/files/c4d16971-7232-4983-be9a-7bbd42efd0ef.png)

The `help` feature is incomplete as seen above. Two main issues are:
1. The help window is too big, it exceeds the user's laptop screen (for me personally). The close button cannot be fully seen either.
2. An empty white screen is displayed which probably should be replaced by the command summary or something that shows the features of the app

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: t1mzzz/ped#7

**Comment by yuehernkang** [comment]
Duplicate Issue #154

**Comment by misterpuffin** [comment]
Closed by https://github.com/AY2223S1-CS2103-W14-1/tp/pull/237
