### ISSUE TITLE
[PE-D][Tester C] `edit -p` command does not edit the property's tags

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-W14-1/tp#150]
Steps to reproduce:

1. Type `edit -p 1 t/Test` in the command box.
2. Press Enter.
3. Open `data/propertyDirectory.json`.
4. The JSON property `tagged` is an empty array, although the property is successfully edited.

![image.png](https://raw.githubusercontent.com/peppapighs/ped/main/files/14129a6a-49ac-480b-87ea-845da25d0902.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: peppapighs/ped#8

**Comment by zacchaeuschok** [comment]
Our `Property` class contained a bug. Easily fixable.
