### ISSUE TITLE
[PE-D][Tester A] Exception thrown when launching the help window, and white box shown in bottom half of help window.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-W14-1/tp#154]
When launching the help window, an exception FileSystemNotFound is thrown.

![image.png](https://raw.githubusercontent.com/lesterong/ped/main/files/66279e7b-9ca3-490e-a7c3-292c44d170b8.png)

The help window opens as expected, but there is a huge white box, which I think is not the intended behaviour.

![image.png](https://raw.githubusercontent.com/lesterong/ped/main/files/f9eda44f-3e6e-409a-bd19-98ec5c8212a7.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lesterong/ped#3

**Comment by misterpuffin** [comment]
Was supposedly fixed in a Closed PR, but need to test with JAR file.
