### ISSUE TITLE
[PE-D][Tester B] tag parameter with spaces

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-W14-1/tp#158]
tried to put in `near me` tag for property 1, this error message pops out. maybe can clarify further that tag names should also not contain spaces?

![image.png](https://raw.githubusercontent.com/maryjess/ped/main/files/28587819-a3e7-4968-a3e8-3726eea6ec06.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: maryjess/ped#12

**Comment by zacchaeuschok** [comment]
Think we should specify that `tag` names should only be alphanumeric and no more than one word in the docs.

**Comment by misterpuffin** [comment]
Updated UG in https://github.com/AY2223S1-CS2103-W14-1/tp/pulls?q=is%3Apr+is%3Aclosed
