### ISSUE TITLE
[PE-D][Tester A] Error handling for clear can be improved, since it is actually a known command.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-W14-1/tp#162]
Better error handing could have been done for the `clear` command. When keying in the `clear` command, it says unknown command, when actually it is known, just that I am missing the demarcators.

![image.png](https://raw.githubusercontent.com/lesterong/ped/main/files/f1a8cf57-2b13-4da9-a8d2-07895a521e13.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: lesterong/ped#5

**Comment by misterpuffin** [comment]
Fixed by https://github.com/AY2223S1-CS2103-W14-1/tp/pull/224
