### ISSUE TITLE
[PE-D][Tester E] Select -c does not show which property client is interested in

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-W14-1/tp#183]
When select -p is done on test1, it shows Casey as interested.

![image.png](https://raw.githubusercontent.com/therealdaofu/ped/main/files/2729d090-1e0f-4a98-a742-72be1cca5e1c.png)

However, when select -c on Casey now, it does not list test1 as his interested property.

![image.png](https://raw.githubusercontent.com/therealdaofu/ped/main/files/ea1b1917-76d2-4bea-8d28-ca063c20fa94.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: therealdaofu/ped#14

**Comment by lkwlkww** [comment]
This should be a feature flaw, since this part of the feature has not been implemented. We should update the UG to describe the current version of this feature (i.e., since interested clients/properties do not update both ways, users have to manually update it on both ends)
