### ISSUE TITLE
Type command not accepted as a valid command

### ISSUE THREAD

**Issue by lkwlkww** [AY2223S1-CS2103-W14-1/tp#215]
Currently, the type command is not accepted as a valid command. As a confirmation, I checked the source code and noticed that the `TypePropertyCommand` is not accounted for in `CondoneryParser`. Perhaps previously, some code got lost when fixing merge conflicts.

We should fix this since the type command is a feature that had already been implemented in v1.3.

Screenshot:
![IMAGE 2022-11-03 14:12:49](https://user-images.githubusercontent.com/65090312/199657579-996eda1e-8a1d-40bc-8fa6-35c2f5276e09.jpg)

**Comment by yuehernkang** [comment]
yes this has been fixed in #208
